### ISSUE TITLE
bugherd integration

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#103]
Bugherd is not visible in the production tier. It seems to work for users who have installed the browser extension for Chrome or Safari, but there is no support for Firefox (due to a security model change) and no plans for future support. I don't think we can ask users to install this extension (and some users may not have admin privs on their machine) so we must add the bugherd script to the <head> tag of the site.

Instructions @ https://support.bugherd.com/hc/en-us/articles/204171450-Installing-the-Script
That page also states that we can reach out to support@bugherd.com  for assistance. Perhaps they will have some experience weaving their code into a React app?

**Comment by caseychoiniere** [comment]
If you want to pre-populate email addresses from the current user, the bugherd script can't be in the head tag of index.erb. I had moved it out of index.erb into the main app.jsx page so that I could pull the email address from the current user object. If the script tag is in index.erb I don't have access to the current user object from the React application. So, do you want me to put the tag back in the head tag of index.erb?

**Comment by erichhuang** [comment]
Dangit. So can't have cake and eat it too...

**Comment by jonturneratduke** [comment]
Casey, can you reach out to support@bugherd.com to learn if they have encountered this before and can propose a workaround?

**Comment by caseychoiniere** [comment]
Typing an email right now

**Comment by caseychoiniere** [comment]
Moved this to index.erb for now so it will show in production. I'll leave it open until support@bugherd gets back to me.

**Comment by jonturneratduke** [comment]
Sorry I forgot to mention they are in Australia, so it's around 8:30am now (5pm here, 2pm your time)

**Comment by caseychoiniere** [comment]
This is the reply from Bugherd support 

```
Hi Casey,

Thanks for getting in touch.

If you're using the js snippet, then this will actually show the sidebar without needing to install the browser extension - you don't need one to power the other, but the js is for when installing a browser extension isn't possible.

Unfortunately there's no way to pre-populate the user's email address based on who the current user is, although you can make the email address a compulsory field, if that would work?

Regards,
Dan.
```

**Comment by erichhuang** [comment]
Should we try to push through to a higher level person?

**Comment by erichhuang** [comment]
I see the bugherd js in the `<head>` tag, but I still don't see it in the app.

**Comment by erichhuang** [comment]
Wonder why it still it isn't showing up.

**Comment by caseychoiniere** [comment]
I think you're supposed to use separate project keys for each instance. So right now we just have just one but we're running three instances. Based on [these docs](https://support.bugherd.com/hc/en-us/articles/204171570) but that still doesn't make sense because Bugherd shows fine on chrome for all instances. I'm going to change so each dev/uatest/prod use their uniquely assigned keys. If this doesn't work I'll go ahead and file another help ticket. 

> Incorrect project key
> 
> If you have multiple projects, it's possible that the incorrect widget was installed on the site. So someone who is a collaborator on project A but project B's widget is loaded, then the sidebar won't show. Note that if you use Web Developer tools, the HTTP error code BugHerd for this issue is: 422. This error code indicates you are logged in, but you are not a member of the project.

Looking at Bugherd docs, they also say you have to be logged in to see the sidebar. I still don't know if this is the case though as I see it in chrome after removing the extension. 

> Not logged in
> 
> The BugHerd sidebar only shows to authenticated users who have an account on www.bugherd.com. BugHerd uses a 3rd party cookie to remember your login so that the sidebar will show on your site for all the invited users. It's possible that cookies have been deleted, or that you are using a different browser or different computer from when you last logged into BugHerd.

[https://support.bugherd.com/hc/en-us/articles/204171570-Sidebar-not-appearing-](https://support.bugherd.com/hc/en-us/articles/204171570-Sidebar-not-appearing-)

**Comment by caseychoiniere** [comment]
Here's the key. Unfortunately, you have to be logged into the Bugherd website in the same browser in order to see the widget.
First you need to invite users with an email. Then they sign up and log into the website, then the widget will show up on the screen. I just tested it on Firefox and it shows up once I log into the Bugherd website. If I log out, the widget disappears. It looks like they just keep you logged in unless you explicitly log out. I've only ever logged in once on Chrome and I'm still logged in (the reason why it shows in Chrome). Might be an issue with shared computers and using Bugherd effectively. Not as seamless as we had hoped.

From their site:

> You need to be logged into BugHerd (the website) in the same browser you use BugHerd (the widget).

Sorry for the bad news. I'm going to close this.

**Comment by caseychoiniere** [comment]
I think we should try putting the script back into the React app though. It should work fine and maybe I can get the email addresses pre-populating for us. Although, if the user needs to be logged in in order to use the service, we'll have their email anyways when they file the issue.

**Comment by jonturneratduke** [comment]
I've opened a ticket with BugHerd and asked them to clarify.
