### ISSUE TITLE
Looping log in screen

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#220]
**Sender**: alm90@duke.edu
**Comment**: I encountered a looping log in screen in Google Chrome.  I was able to log in successfully in IE.
[Open #34 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/34)

![Usersnap Feedback - I encountered a looping log in screen in Google Chrome.  I was able to log (...)](https://usersnappublic.s3.amazonaws.com/2016-03-14/18-08/da654372-4261-4f4b-832f-3e38a9bdf54e.png)

**Browser**: Microsoft Internet Explorer 11 (Windows 7)
**Referer**: [https://dataservice.duke.edu/portal/#/home](https://dataservice.duke.edu/portal/#/home)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 780

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Not entirely sure if this is the cause but likely. I found out that the expiration on the api_token has been changed from 4 hours to 2 hours. I have set the api_token cookie to explicitly expire at 4 hours. So, since then it's been changed to 2 hours and now we've got stale cookies hanging around again.

**Comment by caseychoiniere** [comment]
Fixed the expiration time. This can go out with the next build. I'm 99% sure this was the issue.
