### ISSUE TITLE
Usersnap Feedback - Weird indenting thing happening with unicode characters. The folder moves [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#226]
**Sender**: jonathan.turner@duke.edu
**Comment**: Weird indenting thing happening with unicode characters. The folder moves to the left. I'll share this project w/Casey to confirm.
[Open #38 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/38)

![Usersnap Feedback - Weird indenting thing happening with unicode characters. The folder moves (...)](https://usersnappublic.s3.amazonaws.com/2016-03-18/20-01/18c7f194-81cb-4b66-a4a9-28174fa2f417.png)

**Browser**: Chrome 49 (Mac OS X Mavericks)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/folder/0cd35bae-527e-4e8a-aafd-475eafeda9b8](https://dev.dataservice.duke.edu/portal/#/folder/0cd35bae-527e-4e8a-aafd-475eafeda9b8)
**Screen size**: 1680 x 1050 **Browser size**: 2454 x 1498

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I think this is simply because the unicode characters take up more space than regular characters. I am currently truncating the title at a certain amount of characters to make sure it always fits. But, with unicode it doesn't. I can't imagine a lot of people naming their folders/files with a big long string of unicode though. Probably rare enough that it doesn't really matter???

**Comment by jonturneratduke** [comment]
Ah, that's makes sense. And no, long unicode strings are not going to be a common occurrence. Thanks.
