### ISSUE TITLE
Usersnap Feedback - I'd like the current version to be pretty obvious in the UI

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#255]
**Sender**: erich.huang@duke.edu
**Comment**: I'd like the current version to be pretty obvious in the UI
[Open #47 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/47)

![Usersnap Feedback - I'd like the current version to be pretty obvious in the UI](https://usersnappublic.s3.amazonaws.com/2016-04-02/00-28/02adbe19-fdc4-4ed7-ad1d-6a6521161e0a.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18](https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
They'll need to add version to the file object in order to do this. But I agree we should have this, it makes sense. Should I open an issue in DDS for this? @mgardnerpsu @erichhuang

**Comment by mgardnerpsu** [comment]
I made the following design assumptions for file versioning (_perhaps the wrong assumptions_):
1. A file resource (i.e. `kind = dds-file`) represents the **current file** - it is **NOT** a version from a design standpoint.
2. Versions represent prior file history (i.e. `kind = dds-file-version`) -  they are created when the current file is assigned a new `upload.id` value.

In the current design, the **current file** is where key relationships to _tags, properties, parent path (folder, project), etc._ exist - versions are composite parts of a file and not standalone file resources - they inherit properties mentioned above from file.  This seems to have created some confusion from a UX/user experience standpoint.  I see several options here to improve usability/clarity for end user:
1. I can refactor API to make versions standalone file resources.
2. I can simply add version number to the current file resource, but this could lead to some confusion because it is not truly a version from a design standpoint - it is a `dds-file` not a `dds-file-version`.
3. OR we can work on UX presentation to make the current design clearer to the end user.

Option 1 will be technically more complicated and require code rework
Option 2 & 3 will be technically simpler, but we need to make sure users (as well as developers) have clarity

Thoughts and feedback welcome...

**Comment by caseychoiniere** [comment]
I would vote for **2.** if I had to make a choice. Is there a way to implement this so that it doesn't interfere with the current design paradigm? **3.** is also fine if you have a good solution. For the single file view (the screenshot above), it would be fairly easy for the client to make a guess as to what "version number" the current file is and display this to the user. The more difficult part comes when you have a list of 20 files and you want to display a version for each list item. Then you wouldn't be able to ascertain this information without a ton of overhead.

**Comment by dmann** [comment]
I just talked it over with @dmlond and we have an option 4. A file version is created when the file is created. A new file version is created when the file is updated with a new upload.id. It could be beneficial to add a current_file_version attribute to the file payload, which returns the file_version.id as well as version number. This would allow the UI to link to the "latest" (/files/:file.id) or the "latest version" (/file_versions/:file.current_version.id). Does this make sense? Is it overkill?

**Comment by caseychoiniere** [comment]
So  (/files/:file.id) would no longer point to the most current file upload? Do I understand that correctly? That would require changes to routing in the UI.

**Comment by caseychoiniere** [comment]
Never mind, I think I understand now.  (/files/:file.id) would still point to the latest file upload. There would just be a separate id for the current_file_version attribute.

**Comment by mgardnerpsu** [comment]
@dmann @dmlond @caseychoiniere 
I have thought about this for 30 seconds and I think it is a great solution - seems fairly simple to implement within current model and will provide clarity to user.  I will change Apiary to incorporate this design unless there are objections.
