### ISSUE TITLE
Usersnap Feedback - I uploaded a 905.4 MB file to the ORI Infrastructure project and now I don[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#282]
**Sender**: chris.short@duke.edu
**Comment**: I uploaded a 905.4 MB file to the ORI Infrastructure project and now I don't see the file. Thoughts?
[Open #55 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/55)

![Usersnap Feedback - I uploaded a 905.4 MB file to the ORI Infrastructure project and now I don(...)](https://usersnappublic.s3.amazonaws.com/2016-04-12/21-22/4633e6d0-2007-484c-9449-ee4f486b8407.png)

**Browser**: Chrome 49 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/portal/#/project/d21a3281-c38f-4ed2-bd33-879c7f7fd8e8](https://dataservice.duke.edu/portal/#/project/d21a3281-c38f-4ed2-bd33-879c7f7fd8e8)
**Screen size**: 1920 x 1080 **Browser size**: 1600 x 918

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
That's a first. Did you refresh the page?

**Comment by caseychoiniere** [comment]
@jonturneratduke @dmlond Chris said he saw the success message that the file had uploaded.  You only get the success message when the portal does a  final `post/file` call to DDS and DDS returns a 201. So if he got that then according to DDS the file was created. I'm wondering if this failed in DDS rather than the portal? Might be worth looking into more.

**Comment by dmlond** [comment]
what environment is this running on? dev, uatest, prod?  I cannot find this project in prod.

**Comment by dmlond** [comment]
it looks right to me in the backend.  The project is there. It has one DataFile github-enterprise-2.5.4.ova, with a completed upload, and the file is stored on the swift backend.

**Comment by jonturneratduke** [comment]
Yeah, this was on Production. He initially uploaded the file to the project root (no subfolder). After creating the feedback ticket, he created a subfolder and (re)uploaded the file to the subfolder. This time it worked.  (And yes, he did refresh the page. Also shared the project with me so I could have a look.)

**Comment by caseychoiniere** [comment]
So, it sounds like it didn't work the first time then? Otherwise there would be 2 identical files on the swift backend. Well, I guess we'll have to see if this comes up again and follow up from there. Like I said earlier, the only way a success toast is kicked off in the portal is if DDS returns a 201 status for `post/file`

**Comment by jonturneratduke** [comment]
Yes, exactly -- it failed the first time, worked the second.

**Comment by caseychoiniere** [comment]
Closing for now
