### ISSUE TITLE
Usersnap Feedback - Can we put a notification to users that IE is not supported... also provid[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#321]
**Sender**: James.fayson@duke.edu
**Comment**: Can we put a notification to users that IE is not supported... also provide a list of supported browsers
[Open #65 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/65)

![Usersnap Feedback - Can we put a notification to users that IE is not supported... also provid(...)](https://usersnappublic.s3.amazonaws.com/2016-04-25/20-47/beba9ecc-cc88-4e6d-baa3-4e4e692a9931.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/](https://dataservice.duke.edu/#/)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 769

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
IE is supported. Unfortunately IE doesn't like to get with the times like other browsers and therefore tends to have more bugs, more often. I did some testing on IE on Friday and have found a few bugs that I will fix this afternoon. Is there something in particular that was noticed here and prompted this feedback? If so, please advise so that I can fix. Thank you
