### ISSUE TITLE
Usersnap Feedback - I uploaded a new version of a document using the "Upload New Version" feat[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#352]
**Sender**: lauren.horne@duke.edu
**Comment**: I uploaded a new version of a document using the "Upload New Version" feature.  When I click File Versions and select the new version, the window goes away and doesn't let me download the new version.
[Open #72 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/72)

![Usersnap Feedback - I uploaded a new version of a document using the "Upload New Version" feat(...)](https://usersnappublic.s3.amazonaws.com/2016-06-10/16-47/2c73f0b5-c5eb-45b9-a7b6-d3ff43576442.png)

**Browser**: Firefox 46 (Mac OS X Yosemite)
**Referer**: [https://dataservice.duke.edu/#/file/0410dbdd-2d05-4a0e-95a4-85410434d643](https://dataservice.duke.edu/#/file/0410dbdd-2d05-4a0e-95a4-85410434d643)
**Screen size**: 1280 x 800 **Browser size**: 2560 x 1236

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'm unable to reproduce this using FF 46 or any other browser. Not sure what is happening for this user. Also, the most current version is at "the top of the stack", meaning they shouldn't have to navigate into the file versions list to download the most recent version. Perhaps this is confusing for some people??? Right now in the version list, the most recently uploaded version is displayed as `Current Version: xyzabc123`. If the user clicks this version it simply closes the version list because they are already viewing the most current version. I can see the download button on the screenshot. That button should download the file they're trying to download
