### ISSUE TITLE
Usersnap Feedback - Default to current Project?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#449]
**Sender**: erich.huang@duke.edu
[Open #87 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/87)
**Notes**:
- (1) Default to current Project?
- (2) You're probably aware that autocomplete doesn't work until user types a space or random character

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-13/19-49/648a6d52-b892-4b98-bfc0-bacc95e2e3f8.png'>![Usersnap Feedback - Default to current Project?](https://usersnappublic.s3.amazonaws.com/2016-09-13/19-49/ece2f734-19a9-48f4-a387-bf6d3ad3c9af.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-13/19-49/648a6d52-b892-4b98-bfc0-bacc95e2e3f8.png'>Download original image</a>

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/file/942cb8cc-c35f-4cd7-8c2f-e3406558f014](https://dev.dataservice.duke.edu/#/file/942cb8cc-c35f-4cd7-8c2f-e3406558f014)
**Screen size**: 2560 x 1440 **Browser size**: 1313 x 1329

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
1.) It now will default to current project. Good suggestion, thank you.

2.) This is because if I populate all of the files into the autocomplete datasource it can have a significant lag and can freeze up if there are hundreds (or thousands) of files. So to avoid this I require a search based on text and then only populate the data source with relevant files. I'm checking for white space at the beginning of the text field so it shouldn't populate anything with an empty white space
