### ISSUE TITLE
Folder/file search is not recursive [Search]

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service-portal#48]
When searching for file from project root context - search filter does not recurse into subfolders.

**Comment by caseychoiniere** [comment]
Should remove search for release. It is page level at the moment.

**Comment by caseychoiniere** [comment]
Removed search until can implement proper recursive search function. Having a search bar at the top of the app that only searches page level might be confusing to the user.

**Comment by dmann** [comment]
The project/folder children endpoints accept a name_contains parameter that handles recursive search:

http://docs.dukedataservices.apiary.io/#reference/search-project/folder-children/search-project-children

**Comment by caseychoiniere** [comment]
I'm aware of this. Just hadn't implemented full search yet. Search was a page level react component. Will work on implementing this when I return.

**Comment by caseychoiniere** [comment]
Closing and adding to issue #47

**Comment by caseychoiniere** [comment]
@dmann @mgardnerpsu The issue with the search endpoints is that they are never true global search. If the user is in the project root and they perform a search, they are only returned the project children. If they're in a folder, they only get the children of the folder they are in. This same functionality could be performed with a simple javascript filter, in fact that's what I had in place before. It's misleading to the user if they think search is global and it's not. In order to provide useful search, we probably need different search capability. It could maybe be possible to use the current endpoints but the result would be so contrived and would require so many server calls and overhead that it wouldn't be a great or useful solution.What do you think?

**Comment by caseychoiniere** [comment]
@dmann @mgardnerpsu  bump

**Comment by mgardnerpsu** [comment]
@caseychoiniere I am working with API team on proposed design for search (full-text and boolean filter based search) that should address the gap you outlined above.  I hope to have something drafted by early next week and will be looking for your feedback on usability from portal search perspective.
