### ISSUE TITLE
Usersnap Feedback - I am receiving Failed to Add a New Relationship when I am attempting to up[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#552]
**Sender**: dma34@duke.edu
**Comment**: I am receiving Failed to Add a New Relationship when I am attempting to update the Provence of files with a new activity and a new relationship

[Open #108 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/108)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-12/16-07/3f42197a-9889-424b-8f8d-cd13a13b9b30.png'>![Usersnap Feedback - I am receiving Failed to Add a New Relationship when I am attempting to up(...)](https://usersnappublic.s3.amazonaws.com/2017-01-12/16-07/e06fea94-15e3-40d4-aaed-335cc19a9d52.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-12/16-07/3f42197a-9889-424b-8f8d-cd13a13b9b30.png'>Download original image</a>

**Browser**: Chrome 55 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/file/85fb7478-f674-4d5a-b452-892eb6775556](https://dataservice.duke.edu/#/file/85fb7478-f674-4d5a-b452-892eb6775556)
**Screen size**: 1536 x 864 **Browser size**: 1536 x 760

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
This happens when you create a "was generated by" relation between a file and activity and then delete that relation and try to create a "used" relation between the same file and activity. It errors with a `400 bad request`. It also happens if you create a "used" relation, delete it and then try to create a "was generated" relation. This is a DDS issue not a portal issue
