### ISSUE TITLE
Usersnap Feedback - Firefox bug: When I attempt to select one or more files via the checkbox, [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#643]
**Sender**: jonathan.turner@duke.edu
**Comment**: Firefox bug: When I attempt to select one or more files via the checkbox, it instead selects the file and navigates to the file details. Donald and I have both seen this. We think this is Firefox-only -- we don't see the problem in Chrome. I'm up-to-date with v53.0
[Open #119 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/119)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-20/21-02/b7d4b03a-585b-48bc-bc5b-685cab505d6d.png'>![Usersnap Feedback - Firefox bug: When I attempt to select one or more files via the checkbox, (...)](https://usersnappublic.s3.amazonaws.com/2017-04-20/21-02/f6910842-3bba-4c21-90aa-afe5c65171d3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-20/21-02/b7d4b03a-585b-48bc-bc5b-685cab505d6d.png'>Download original image</a>

**Browser**: Firefox 53 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/folder/123e0213-0b7c-4b79-a89f-9b774690eb02](https://dataservice.duke.edu/#/folder/123e0213-0b7c-4b79-a89f-9b774690eb02)
**Screen size**: 1680 x 1050 **Browser size**: 923 x 701

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke Thanks for reporting this. It has now been fixed and I've completely redesigned the list items component.  I'm glad this bug showed up because it gave me cause to redo this part of the app. I never really liked the old list items component I was using so I decided to use a data table that I had implemented in a toy app I was building in my spare time. It is 1000x cleaner in my opinion. Check it out when you get a chance.
