### ISSUE TITLE
Logo missing

### ISSUE THREAD

**Issue by Donmurry** [Duke-Translational-Bioinformatics/duke-data-service-portal#692]
The Duke DS logo is missing when using this URL https://dataservice.duke.edu/portal/#/login, but is shows up when visiting this URL https://dataservice.duke.edu/#/login.

The former URL has been distributed to other Duke websites, and might be easily be changed. Can this be fixed?

**Comment by caseychoiniere** [comment]
I believe I logged an issue for this last year. I think it has something to do with where the static assets are being served in the Ruby app. The URL breaks the path to the .png logo. I'll look into it more, I'm just now getting back to civilization.

**Comment by caseychoiniere** [comment]
https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/issues/472

**Comment by Donmurry** [comment]
@dmlond @dmann  Can we look at this from our end to make sure we're giving Casey what he needs?

**Comment by dmlond** [comment]
Its not a ruby app anymore. Its a node.js express application. I believe the problem is in how the image is referenced as a relative path
<img src="images/dukeDSLogo.png" style="max-width: 26.333%;">
which causes it to work from /#/login (because it renders to '/images/dukeDSLogo.png') 

but not from /portal/#/login (because it renders relative to '/portal/images/dukeDSLogo.png')

@caseychoiniere can you change this to an absolute path?
<img src="/images/dukeDSLogo.png" style="max-width: 26.333%;">

**Comment by caseychoiniere** [comment]
Thanks @dmlond Correct, it's not a Ruby app anymore, I was referencing an old issue from memory while on a bus, bad idea :) 

I've tried an absolute path and it's not working but I'll get it figured out.
