### ISSUE TITLE
Object `hash` is not being displayed

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#91]
On the web app, it's showing as 'null:null'
![screen shot 2016-01-22 at 14 15 23](https://cloud.githubusercontent.com/assets/386675/12520466/c5a263ba-c112-11e5-9d78-d5459cb621c5.png)

**Comment by caseychoiniere** [comment]
Hash shows up on older files that were created  but not on newly uploaded files. Hash value and type in the upload object returned by DDS are null. Could this be due to the change that was made not requiring the whole file to be hashed? 
First screen shot is a new upload. No hash returned by DDS.
![screen shot 2016-01-22 at 11 58 04 am](https://cloud.githubusercontent.com/assets/10411174/12521517/e7b5511e-c0ff-11e5-99d7-c69d1fbb31c8.png)

Second screenshot is an old upload, DDS returns hash
![screen shot 2016-01-22 at 11 58 49 am](https://cloud.githubusercontent.com/assets/10411174/12521551/0b85e298-c100-11e5-9ea2-375c6922723c.png)

**Comment by caseychoiniere** [comment]
Perhaps this is a DDS issue?

**Comment by caseychoiniere** [comment]
Removing from UI for now.
